name: 'PR Sizer'
description: 'Github action in charge of labeling with t-shirt sizing the PRs based on the number of lines modified (added, updated and deleted)'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  size_s:
    description: 'Maximum number of lines for a S size'
    required: true
  size_m:
    description: 'Maximum number of lines for a M size'
    required: true
    default: '500'
  size_l:
    description: 'Maximum number of lines for a L size'
    required: true
  size_xl:
    description: 'Maximum number of lines for a XL size'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.size_s }}
    - ${{ inputs.size_m }}
    - ${{ inputs.size_l }}
    - ${{ inputs.size_xl }}
branding:
  icon: activity
  color: blue
