name: pr-sizer
description: Github action in charge of labeling with t-shirt sizing the PRs based on the number of lines modified (added, updated and deleted)
runs:
  using: docker
  image: Dockerfile
branding:
  icon: activity
  color: blue
