name: 'PR Sizer'
on: pull_request
jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    name: Size PRs with labels
    steps:
      - uses: actions/checkout@v1
        with:
          s_max_size: '40'
          m_max_size: '200'
          l_max_size: '600'
          xl_max_size: '1000'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}